### PR TITLE
Support booking for more than one person.

### PR DESCRIPTION
**Pull request by tomasskare**

### CODE REVIEW

**Review by jonkpirateboy — COMMENTED** [review]
Great start! We need to have names for all people though.

**Comment by tomasskare** [comment]
Ah, right. I haven't actually been able to get to the booking part of the process yet, so I guess the automatic verify fails now. The searching of time slots works anyway.

I'll see if I can make the rest work too.

**Comment by fredentoft** [comment]
Ok, not the prettiest solution, but:

```
firstName = ['Test1','Test2','Test3','Test4'] # Your first name
lastName = ['Test1sson','Test2sson','Test3sson','Test4sson'] # Your last name
```

And

```
            # Fill out your name
            for pers in range(1, numberOfPeople+1):
              web.find_element(by=By.XPATH, value='//*[@id="Customers_'+str(pers-1)+'__BookingFieldValues_0__Value"]').send_keys(firstName[pers-1])
              web.find_element(by=By.XPATH, value='//*[@id="Customers_'+str(pers-1)+'__BookingFieldValues_1__Value"]').send_keys(lastName[pers-1])
              web.find_element(by=By.XPATH, value='//*[@id="Customers_'+str(pers-1)+'__Services_0__IsSelected"]').click()
```

**Comment by fredentoft** [comment]
Possibly also could use just firstname as an array and let 
numberOfPeople = len(firstname)

**Comment by johanbrook** [comment]
Also: https://github.com/jonkpirateboy/Pass-fur-alle/pull/2

**Pull request closed without merging**
