### PR TITLE
Headless ChromeDriver

### PR DESCRIPTION
**Pull request by larsmjoh**
Nu kör den headless, printar bokningen och frågar om man vill bekräfta (J/n)

### CODE REVIEW

**Comment by jonkpirateboy** [comment]
Has this been tested on MacOS and Linux too?

**Comment by larsmjoh** [comment]
It has been tested on Debian 22.04 under WSL2, without an X-server running on the Windows host or DISPLAY env set.
Not on a "bare metal" Linux though...

**Comment by jonkpirateboy** [comment]
Ok, I will test it on MacOS and Linux before merging, so it can take some time. I have life too .. ;) But anyway, a million thanks for helping out!

**Comment by larsmjoh** [comment]
Should have used branches from the start...

**Comment by soma** [comment]
Can confirm this works under ubuntu linux 20.04 running on "bare metal" ie a vanilla vps install.

**Comment by m0ar** [comment]
I can confirm it works out of the box on Arch with the latest released versions of all dependencies:
- `google-chrome-100.0.4896.60-1`
- `chromedriver-beta-100.0.4896.20-1` 
- `python-selenium-3.141.0-4`

**Comment by jonkpirateboy** [comment]
This is now closed since Pass für alle has changed from Python to Javascript

**Pull request closed without merging**
