### PR TITLE
Made pagereload to avoid having to timeout for 15 sec

### PR DESCRIPTION
**Pull request by margu421**
Replaced // jQuery('input[name="' + localStorage.getItem('TimeSearch') + '"]').click();  
with 
window.location.reload();

### CODE REVIEW

**Comment by j1MP** [comment]
In this case, using refresh-function. Would it not be possible to refresh the page after less time, instead of waiting 15 seconds.

**Comment by j1MP** [comment]
super useful, thanks.

**Comment by jonkpirateboy** [comment]
I didn't get it to work

**Comment by margu421** [comment]
Ok! Worked on my machine 🙂

**Pull request closed without merging**
