### PR TITLE
Experimental support for registering more people

### PR DESCRIPTION
**Pull request by johanbrook**
My Python is rusty, but I made this for helping a friend.

It adds a list of people to register in a single booking, instead of only one. Only first and last names are needed. Use this if you'd like, or not 🌻

### CODE REVIEW

**Comment by jonkpirateboy** [comment]
Quick and dirty solution for registering multiple people https://pastebin.com/qa4S9aUx

**Comment by jonkpirateboy** [comment]
If I get the time, I'll build this as an option to the script.

**Comment by jonkpirateboy** [comment]
And thanks for your modifications! Those will be used if I do the changes, much better than my quick and dirty solution! <3

**Comment by johanbrook** [comment]
No worries!

**Pull request closed without merging**
