### PR TITLE
Manual fixes for verification steps added

### PR DESCRIPTION
**Pull request by ispjstfu**
Added a manual step to stop the script so that the verification can be solved by a human before moving on to the booking area. Makes the original script work like before after the verification is solved.

### CODE REVIEW

**Comment by ispjstfu** [comment]
Note: After a time is found, it still needs manual verification again, but at least the most tedious part is fixed, finding a time. I will look at adding the rest in a new commit later today.

**Comment by ispjstfu** [comment]
Now I've also added a fix for the second verification step after a time is found, plus a click that the "important information" was read so that the script can move on and confirm the booking.

**Comment by jarpalmer1** [comment]
Hi thank u so much for ur update!!! I´m getting this error when trying 
image. What do I do wrong? Or how do I fix it? Thank u!!!!!

**Comment by jonkpirateboy** [comment]
I will test this later today! Thanks! ❤️

**Comment by jonkpirateboy** [comment]
Unfortunately this doesn't work for me, I get redirected to the "För många anrop" page. Does it still work for you?
I also needet to change the `startButton` to `web.find_element(by=By.XPATH, value='//*[@value="Boka ny tid"]')`, to get the first click working.

**Comment by geekteq** [comment]
> Unfortunately this doesn't work for me, I get redirected to the "För många anrop" page. Does it still work for you? I also needet to change the `startButton` to `web.find_element(by=By.XPATH, value='//*[@value="Boka ny tid"]')`, to get the first click working.

Credit where credit is due. My pull request is based on @ispjstfu fix. I just added another manual thing along the way - that made things work for me. So most of the props goes to @ispjstfu in my book :)

**Comment by jonkpirateboy** [comment]
@geekteq, defenetly. Thanks to you both! <3

**Pull request closed without merging**
