### PR TITLE
Use the function "First available time"

### PR DESCRIPTION
**Pull request by granstubbe**
Added the functionality of using "First available time". It goes a lot faster and doesn't require clicking through each day. Use it if you like! :)

### CODE REVIEW

**Comment by tedpelas** [comment]
It seems they are mitigating the "scripting problem" now.
Screenshot 2022-03-22 at 21 53 28

**Comment by daverstam** [comment]
This worked really nice, instantly got a passport-time 👍

**Comment by jonkpirateboy** [comment]
Nice! I think I'll make it as an option, so the user can run either one.

**Review by jonkpirateboy — APPROVED** [review]

**Comment by jonkpirateboy** [comment]
I've merged your code, but added `firstDate = False` for users to choose to use this or not. Since this seems to be a cat and mouse game the developers of the queue system can make changes any time. Like for instance limiting the use of "First available time" a couple of days ago. Your addition is great if either approach stops working.

**Pull request merged**
