### PR TITLE
Book for multiple people + chromedriver bug workaround

### PR DESCRIPTION
**Pull request by maxramqvist**
This:
- works for booking for multiple people
- works around a chromdriver bug that affects chromedriver 98 and 99. 97 should be fine. Note - its not the Chrome version, its the chromedriver version

### CODE REVIEW

**Review by jonkpirateboy — COMMENTED** [review]
I tried my script unchanged in Chromedriver 99 without a hitch. Then I tried this and it fails.

```
/Volumes/Rugged/_git/Pass-fur-alle/pass-fur-alle.py:102: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  emailElements = [web.find_element_by_id("EmailAddress"), web.find_element_by_id("ConfirmEmailAddress")]
Traceback (most recent call last):
  File "/Volumes/Rugged/_git/Pass-fur-alle/pass-fur-alle.py", line 84, in clickTimeIfExists
    web.find_element(by=By.XPATH, value='//*[@class="timetable-cells"]').click()
  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 1248, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "/opt/homebrew/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@class="timetable-cells"]"}
  (Session info: chrome=99.0.4844.83)
Stacktrace:
0   chromedriver                        0x0000000104b23370 chromedriver + 4420464
1   chromedriver                        0x0000000104aba940 chromedriver + 3991872
2   chromedriver                        0x000000010471a548 chromedriver + 189768
3   chromedriver                        0x0000000104748ef8 chromedriver + 380664
4   chromedriver                        0x0000000104771bfc chromedriver + 547836
5   chromedriver                        0x000000010473e248 chromedriver + 336456
6   chromedriver                        0x0000000104ae7548 chromedriver + 4175176
7   chromedriver                        0x0000000104afd95c chromedriver + 4266332
8   chromedriver                        0x0000000104b02660 chromedriver + 4286048
9   chromedriver                        0x0000000104afe124 chromedriver + 4268324
10  chromedriver                        0x0000000104add53c chromedriver + 4134204
11  chromedriver                        0x0000000104b15eb0 chromedriver + 4366000
12  chromedriver                        0x0000000104b16014 chromedriver + 4366356
13  chromedriver                        0x0000000104b29a6c chromedriver + 4446828
14  libsystem_pthread.dylib             0x00000001a9b314ec _pthread_start + 148
15  libsystem_pthread.dylib             0x00000001a9b2c2d0 thread_start + 8


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Rugged/_git/Pass-fur-alle/pass-fur-alle.py", line 158, in <module>
    searchPassTime()
  File "/Volumes/Rugged/_git/Pass-fur-alle/pass-fur-alle.py", line 64, in searchPassTime
    clickTimeIfExists()
  File "/Volumes/Rugged/_git/Pass-fur-alle/pass-fur-alle.py", line 128, in clickTimeIfExists
    clickTimeIfExists()
  File "/Volumes/Rugged/_git/Pass-fur-alle/pass-fur-alle.py", line 104, in clickTimeIfExists
    action = ActionChains(web)
NameError: name 'ActionChains' is not defined
```

**Comment by maxramqvist** [comment]
Perhaps its the OS or something else then. The code for multiple people works though (managed a booking this morning and last night).
Great work with the code! :D

**Review by jonkpirateboy — APPROVED** [review]
Fantastic! <3

**Comment by jonkpirateboy** [comment]
Your multiple people fix has been merged, and I changed a few things since I don't want deprecated functions being used. Safe for future use you know. Super thanks for your help. And i like Testina Testlund ;)

**Comment by jonkpirateboy** [comment]
Now I've updated the readme too

**Comment by maxramqvist** [comment]
You did the hard work so thank you :)

I was very impressed by chromedriver as well. Didn't know about it.

**Pull request merged**
