### PR TITLE
do the first button push manually to get past the 'too many requests' …

### PR DESCRIPTION
**Pull request by geekteq**
It seems like it's working for some.

### CODE REVIEW

**Comment by geekteq** [comment]
Contains ispjstfu:verification-fix - just adding another manual thing to bypass automation check (at least on MacOS)

**Comment by jonkpirateboy** [comment]
Strange, this no longer works for me. Can you confirm?

**Comment by geekteq** [comment]
> Strange, this no longer works for me. Can you confirm?

Yeap, I think they found me out somehow :) I get through the first button but get stuck after the first captcha.
Tried to bypass by doing captcha manually but get stuck on the next button as well (even if I do it manually)

So, no, doesn't work anymore

**Comment by geekteq** [comment]
I have to turn this over back to the experts (not that good with selenium myself)
But nice to see "nemoq" getting close to something that may work... but for some reason I keep thinking: "Just put friggin BankID on the booking and be done with it"

**Comment by jonkpirateboy** [comment]
They are protecting the bad booking system instead of fixing the booking system. But they are definitely on their toes.

**Pull request closed without merging**
